#define YA_ECGEN_ERROR_COOL(message) static_assert(false, message)

#define YA_ECGEN_ERROR(message) static_assert(false, message)
#define YA_ECGEN_ERROR_MESSAGE_UNPARITY "YA_ECGEN_: [Argument unparity] Error code doesn't have its message pair."
#define YA_ECGEN_ERROR_MESSAGE_NO_ARGS "YA_ECGEN_: [No members] No member was specified for this enum type."

#define YA_ECGEN___ARGS__0_0(lowercase_name, UPPERCASE_NAME) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_NO_ARGS)
#define YA_ECGEN___ARGS__0_1(lowercase_name, UPPERCASE_NAME, __0__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_2(lowercase_name, UPPERCASE_NAME, __0__, __1__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__};
#define YA_ECGEN___ARGS__0_3(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_4(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__};
#define YA_ECGEN___ARGS__0_5(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_6(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__};
#define YA_ECGEN___ARGS__0_7(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_8(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__};
#define YA_ECGEN___ARGS__0_9(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_10(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__};
#define YA_ECGEN___ARGS__0_11(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_12(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__,YA_ ## UPPERCASE_NAME ## _ ## __10__};
#define YA_ECGEN___ARGS__0_13(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_14(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__,YA_ ## UPPERCASE_NAME ## _ ## __10__,YA_ ## UPPERCASE_NAME ## _ ## __12__};
#define YA_ECGEN___ARGS__0_15(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_16(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__,YA_ ## UPPERCASE_NAME ## _ ## __10__,YA_ ## UPPERCASE_NAME ## _ ## __12__,YA_ ## UPPERCASE_NAME ## _ ## __14__};
#define YA_ECGEN___ARGS__0_17(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_18(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__,YA_ ## UPPERCASE_NAME ## _ ## __10__,YA_ ## UPPERCASE_NAME ## _ ## __12__,YA_ ## UPPERCASE_NAME ## _ ## __14__,YA_ ## UPPERCASE_NAME ## _ ## __16__};
#define YA_ECGEN___ARGS__0_19(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_20(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__,YA_ ## UPPERCASE_NAME ## _ ## __10__,YA_ ## UPPERCASE_NAME ## _ ## __12__,YA_ ## UPPERCASE_NAME ## _ ## __14__,YA_ ## UPPERCASE_NAME ## _ ## __16__,YA_ ## UPPERCASE_NAME ## _ ## __18__};
#define YA_ECGEN___ARGS__0_21(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_22(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__,YA_ ## UPPERCASE_NAME ## _ ## __10__,YA_ ## UPPERCASE_NAME ## _ ## __12__,YA_ ## UPPERCASE_NAME ## _ ## __14__,YA_ ## UPPERCASE_NAME ## _ ## __16__,YA_ ## UPPERCASE_NAME ## _ ## __18__,YA_ ## UPPERCASE_NAME ## _ ## __20__};
#define YA_ECGEN___ARGS__0_23(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_24(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__,YA_ ## UPPERCASE_NAME ## _ ## __10__,YA_ ## UPPERCASE_NAME ## _ ## __12__,YA_ ## UPPERCASE_NAME ## _ ## __14__,YA_ ## UPPERCASE_NAME ## _ ## __16__,YA_ ## UPPERCASE_NAME ## _ ## __18__,YA_ ## UPPERCASE_NAME ## _ ## __20__,YA_ ## UPPERCASE_NAME ## _ ## __22__};
#define YA_ECGEN___ARGS__0_25(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_26(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__,YA_ ## UPPERCASE_NAME ## _ ## __10__,YA_ ## UPPERCASE_NAME ## _ ## __12__,YA_ ## UPPERCASE_NAME ## _ ## __14__,YA_ ## UPPERCASE_NAME ## _ ## __16__,YA_ ## UPPERCASE_NAME ## _ ## __18__,YA_ ## UPPERCASE_NAME ## _ ## __20__,YA_ ## UPPERCASE_NAME ## _ ## __22__,YA_ ## UPPERCASE_NAME ## _ ## __24__};
#define YA_ECGEN___ARGS__0_27(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__, __26__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0_28(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__, __26__, __27__) enum ya_ ## lowercase_name ## _error_codes {YA_ ## UPPERCASE_NAME ## _ ## __0__,YA_ ## UPPERCASE_NAME ## _ ## __2__,YA_ ## UPPERCASE_NAME ## _ ## __4__,YA_ ## UPPERCASE_NAME ## _ ## __6__,YA_ ## UPPERCASE_NAME ## _ ## __8__,YA_ ## UPPERCASE_NAME ## _ ## __10__,YA_ ## UPPERCASE_NAME ## _ ## __12__,YA_ ## UPPERCASE_NAME ## _ ## __14__,YA_ ## UPPERCASE_NAME ## _ ## __16__,YA_ ## UPPERCASE_NAME ## _ ## __18__,YA_ ## UPPERCASE_NAME ## _ ## __20__,YA_ ## UPPERCASE_NAME ## _ ## __22__,YA_ ## UPPERCASE_NAME ## _ ## __24__,YA_ ## UPPERCASE_NAME ## _ ## __26__};
#define YA_ECGEN___ARGS__0_29(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__, __26__, __27__, __28__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__0(__0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__, __26__, __27__, __28__, __29__, __NAME__, ...) __NAME__
#define YA_ECGEN___ARGS__1_0(lowercase_name, UPPERCASE_NAME) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_NO_ARGS)
#define YA_ECGEN___ARGS__1_1(lowercase_name, UPPERCASE_NAME, __0__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_2(lowercase_name, UPPERCASE_NAME, __0__, __1__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__};
#define YA_ECGEN___ARGS__1_3(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_4(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__};
#define YA_ECGEN___ARGS__1_5(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_6(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__};
#define YA_ECGEN___ARGS__1_7(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_8(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__};
#define YA_ECGEN___ARGS__1_9(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_10(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__};
#define YA_ECGEN___ARGS__1_11(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_12(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__, [YA_ ## UPPERCASE_NAME ## _ ## __10__] = __11__};
#define YA_ECGEN___ARGS__1_13(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_14(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__, [YA_ ## UPPERCASE_NAME ## _ ## __10__] = __11__, [YA_ ## UPPERCASE_NAME ## _ ## __12__] = __13__};
#define YA_ECGEN___ARGS__1_15(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_16(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__, [YA_ ## UPPERCASE_NAME ## _ ## __10__] = __11__, [YA_ ## UPPERCASE_NAME ## _ ## __12__] = __13__, [YA_ ## UPPERCASE_NAME ## _ ## __14__] = __15__};
#define YA_ECGEN___ARGS__1_17(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_18(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__, [YA_ ## UPPERCASE_NAME ## _ ## __10__] = __11__, [YA_ ## UPPERCASE_NAME ## _ ## __12__] = __13__, [YA_ ## UPPERCASE_NAME ## _ ## __14__] = __15__, [YA_ ## UPPERCASE_NAME ## _ ## __16__] = __17__};
#define YA_ECGEN___ARGS__1_19(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_20(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__, [YA_ ## UPPERCASE_NAME ## _ ## __10__] = __11__, [YA_ ## UPPERCASE_NAME ## _ ## __12__] = __13__, [YA_ ## UPPERCASE_NAME ## _ ## __14__] = __15__, [YA_ ## UPPERCASE_NAME ## _ ## __16__] = __17__, [YA_ ## UPPERCASE_NAME ## _ ## __18__] = __19__};
#define YA_ECGEN___ARGS__1_21(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_22(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__, [YA_ ## UPPERCASE_NAME ## _ ## __10__] = __11__, [YA_ ## UPPERCASE_NAME ## _ ## __12__] = __13__, [YA_ ## UPPERCASE_NAME ## _ ## __14__] = __15__, [YA_ ## UPPERCASE_NAME ## _ ## __16__] = __17__, [YA_ ## UPPERCASE_NAME ## _ ## __18__] = __19__, [YA_ ## UPPERCASE_NAME ## _ ## __20__] = __21__};
#define YA_ECGEN___ARGS__1_23(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_24(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__, [YA_ ## UPPERCASE_NAME ## _ ## __10__] = __11__, [YA_ ## UPPERCASE_NAME ## _ ## __12__] = __13__, [YA_ ## UPPERCASE_NAME ## _ ## __14__] = __15__, [YA_ ## UPPERCASE_NAME ## _ ## __16__] = __17__, [YA_ ## UPPERCASE_NAME ## _ ## __18__] = __19__, [YA_ ## UPPERCASE_NAME ## _ ## __20__] = __21__, [YA_ ## UPPERCASE_NAME ## _ ## __22__] = __23__};
#define YA_ECGEN___ARGS__1_25(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_26(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__, [YA_ ## UPPERCASE_NAME ## _ ## __10__] = __11__, [YA_ ## UPPERCASE_NAME ## _ ## __12__] = __13__, [YA_ ## UPPERCASE_NAME ## _ ## __14__] = __15__, [YA_ ## UPPERCASE_NAME ## _ ## __16__] = __17__, [YA_ ## UPPERCASE_NAME ## _ ## __18__] = __19__, [YA_ ## UPPERCASE_NAME ## _ ## __20__] = __21__, [YA_ ## UPPERCASE_NAME ## _ ## __22__] = __23__, [YA_ ## UPPERCASE_NAME ## _ ## __24__] = __25__};
#define YA_ECGEN___ARGS__1_27(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__, __26__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1_28(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__, __26__, __27__) const char *ya_ ## lowercase_name ## _conversion_table[] = {[YA_ ## UPPERCASE_NAME ## _ ## __0__] = __1__, [YA_ ## UPPERCASE_NAME ## _ ## __2__] = __3__, [YA_ ## UPPERCASE_NAME ## _ ## __4__] = __5__, [YA_ ## UPPERCASE_NAME ## _ ## __6__] = __7__, [YA_ ## UPPERCASE_NAME ## _ ## __8__] = __9__, [YA_ ## UPPERCASE_NAME ## _ ## __10__] = __11__, [YA_ ## UPPERCASE_NAME ## _ ## __12__] = __13__, [YA_ ## UPPERCASE_NAME ## _ ## __14__] = __15__, [YA_ ## UPPERCASE_NAME ## _ ## __16__] = __17__, [YA_ ## UPPERCASE_NAME ## _ ## __18__] = __19__, [YA_ ## UPPERCASE_NAME ## _ ## __20__] = __21__, [YA_ ## UPPERCASE_NAME ## _ ## __22__] = __23__, [YA_ ## UPPERCASE_NAME ## _ ## __24__] = __25__, [YA_ ## UPPERCASE_NAME ## _ ## __26__] = __27__};
#define YA_ECGEN___ARGS__1_29(lowercase_name, UPPERCASE_NAME, __0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__, __26__, __27__, __28__) YA_ECGEN_ERROR(YA_ECGEN_ERROR_MESSAGE_UNPARITY)
#define YA_ECGEN___ARGS__1(__0__, __1__, __2__, __3__, __4__, __5__, __6__, __7__, __8__, __9__, __10__, __11__, __12__, __13__, __14__, __15__, __16__, __17__, __18__, __19__, __20__, __21__, __22__, __23__, __24__, __25__, __26__, __27__, __28__, __29__, __NAME__, ...) __NAME__
#define YA_ECGEN___GENERATOR__0(lowercase_name, UPPERCASE_NAME, __GEN__, ...) __GEN__(lowercase_name, UPPERCASE_NAME, __VA_ARGS__)

#define YA_ECGEN___GENERATOR__1(lowercase_name, UPPERCASE_NAME, __GEN__, ...) __GEN__(lowercase_name, UPPERCASE_NAME, __VA_ARGS__)

#define YA_ECGEN(lowercase_name, UPPERCASE_NAME, ...) YA_ECGEN___GENERATOR__0(lowercase_name, UPPERCASE_NAME, YA_ECGEN___ARGS__0("empty", ##__VA_ARGS__, YA_ECGEN___ARGS__0_29, YA_ECGEN___ARGS__0_28, YA_ECGEN___ARGS__0_27, YA_ECGEN___ARGS__0_26, YA_ECGEN___ARGS__0_25, YA_ECGEN___ARGS__0_24, YA_ECGEN___ARGS__0_23, YA_ECGEN___ARGS__0_22, YA_ECGEN___ARGS__0_21, YA_ECGEN___ARGS__0_20, YA_ECGEN___ARGS__0_19, YA_ECGEN___ARGS__0_18, YA_ECGEN___ARGS__0_17, YA_ECGEN___ARGS__0_16, YA_ECGEN___ARGS__0_15, YA_ECGEN___ARGS__0_14, YA_ECGEN___ARGS__0_13, YA_ECGEN___ARGS__0_12, YA_ECGEN___ARGS__0_11, YA_ECGEN___ARGS__0_10, YA_ECGEN___ARGS__0_9, YA_ECGEN___ARGS__0_8, YA_ECGEN___ARGS__0_7, YA_ECGEN___ARGS__0_6, YA_ECGEN___ARGS__0_5, YA_ECGEN___ARGS__0_4, YA_ECGEN___ARGS__0_3, YA_ECGEN___ARGS__0_2, YA_ECGEN___ARGS__0_1, YA_ECGEN___ARGS__0_0), __VA_ARGS__) YA_ECGEN___GENERATOR__1(lowercase_name, UPPERCASE_NAME, YA_ECGEN___ARGS__1("empty", ##__VA_ARGS__, YA_ECGEN___ARGS__1_29, YA_ECGEN___ARGS__1_28, YA_ECGEN___ARGS__1_27, YA_ECGEN___ARGS__1_26, YA_ECGEN___ARGS__1_25, YA_ECGEN___ARGS__1_24, YA_ECGEN___ARGS__1_23, YA_ECGEN___ARGS__1_22, YA_ECGEN___ARGS__1_21, YA_ECGEN___ARGS__1_20, YA_ECGEN___ARGS__1_19, YA_ECGEN___ARGS__1_18, YA_ECGEN___ARGS__1_17, YA_ECGEN___ARGS__1_16, YA_ECGEN___ARGS__1_15, YA_ECGEN___ARGS__1_14, YA_ECGEN___ARGS__1_13, YA_ECGEN___ARGS__1_12, YA_ECGEN___ARGS__1_11, YA_ECGEN___ARGS__1_10, YA_ECGEN___ARGS__1_9, YA_ECGEN___ARGS__1_8, YA_ECGEN___ARGS__1_7, YA_ECGEN___ARGS__1_6, YA_ECGEN___ARGS__1_5, YA_ECGEN___ARGS__1_4, YA_ECGEN___ARGS__1_3, YA_ECGEN___ARGS__1_2, YA_ECGEN___ARGS__1_1, YA_ECGEN___ARGS__1_0), __VA_ARGS__) 


YA_ECGEN(
    vector, VECTOR,
    EMPTY, "Vector was empty."
)